In [1]:
4/2

2.0

In [2]:
5.2/2

2.6

In [6]:
import pandas as pd
import numpy as np

In [5]:
series=pd.Series(3,index=['a','b','c'])
series

a    3
b    3
c    3
dtype: int64

In [19]:
a=np.array([1,2,3])

In [9]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.linspace(5,15,10)

array([ 5.        ,  6.11111111,  7.22222222,  8.33333333,  9.44444444,
       10.55555556, 11.66666667, 12.77777778, 13.88888889, 15.        ])

In [17]:
np.vstack(([1,2,3]))

array([[1],
       [2],
       [3]])

In [20]:
np.hsplit(a,2)

ValueError: array split does not result in an equal division

In [22]:
a=np.array([6,5,4])
b=np.array([1,2,3])

In [23]:
c=a-b

In [24]:
c

array([5, 3, 1])